server:
  port: 9999
  tomcat:
    #윈도우기반 파일위치 지정
    accesslog:
      enabled: true
      pattern: "%t %a %s \"%r\" %b (%D ms)"
      directory: log
      suffix: .log
      prefix: access
    basedir: /
spring:
  resources:
    add-mappings: false
  datasource:
      url: jdbc:h2:tcp://localhost/~/buskingbusking
      username: sa
      passowrd:
      driver-class-name: org.h2.Driver
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
          # show_sql: true
      format_sql: true
logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace